export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SESSION_REQUEST = 'SESSION_REQUEST'
export const SESSION_SUCCESS = 'SESSION_SUCCESS'
export const SESSION_FAILURE = 'SESSION_FAILURE'

export const ORGS_REQUEST = 'ORGS_REQUEST'
export const ORGS_SUCCESS = 'ORGS_SUCCESS'
export const ORGS_FAILURE = 'ORGS_FAILURE'

export const CHANNELS_REQUEST = 'CHANNELS_REQUEST'
export const CHANNELS_SUCCESS = 'CHANNELS_SUCCESS'
export const CHANNELS_FAILURE = 'CHANNELS_FAILURE'

export const SET_CURRENT_ORG = 'SET_CURRENT_ORG'
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL'

export const WS_CONNECT = 'WS_CONNECT'
